name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Tesing
        run: |
          make test

      - name: Build binary
        run: |
          make build

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mmszhezhi/fuckworld
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Update the API service2
        uses: appleboy/ssh-action@v0.0.6
        with:
            host: ${{ secrets.SSH_HOST }}
            username: herman
            key: ${{ secrets.SSH_KEY }}
            script_stop: true
            script: |
              cd /home/herman/Desktop/dockers/gin-github-action && docker-compose pull && docker-compose up -d
