name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Update the API service23
        uses: appleboy/ssh-action@v0.0.6
        with:
            host: ${{ secrets.SSH_HOST }}
            port: ${{ secrets.SSH_PROXY }}
            username: herman
            key: ${{ secrets.SSH_KEY }}
            script_stop: true
            script: |
              echo fuck
